In [2]:
import pandas as pd

In [3]:
# Load dataset (CSV)
df = pd.read_csv("Disease_data.csv")

In [4]:
df = df.map(lambda x: x.strip() if isinstance(x, str) else x)

In [5]:
df.head()

,Disease,Fever,Cough,Fatigue,Difficulty Breathing,Gender,Blood Pressure,Unnamed: 7,Cholesterol Level,Outcome Variable
0,Influenza,Yes,No,Yes,Yes,Female,Low,NaN,Normal,Positive
1,Common Cold,No,Yes,Yes,No,Female,Normal,NaN,Normal,Negative
2,Eczema,No,Yes,Yes,No,Female,Normal,NaN,Normal,Negative
3,Asthma,Yes,Yes,No,Yes,Male,Normal,NaN,Normal,Positive
4,Eczema,Yes,No,No,No,Female,Normal,NaN,Normal,Positive

In [6]:
del df['Unnamed: 7']

In [7]:
df.head()

,Disease,Fever,Cough,Fatigue,Difficulty Breathing,Gender,Blood Pressure,Cholesterol Level,Outcome Variable
0,Influenza,Yes,No,Yes,Yes,Female,Low,Normal,Positive
1,Common Cold,No,Yes,Yes,No,Female,Normal,Normal,Negative
2,Eczema,No,Yes,Yes,No,Female,Normal,Normal,Negative
3,Asthma,Yes,Yes,No,Yes,Male,Normal,Normal,Positive
4,Eczema,Yes,No,No,No,Female,Normal,Normal,Positive

In [8]:
# -----------------------------
# 2. Standardize text
# -----------------------------
df = df.replace({
    'yes': 'Yes', 'no': 'No',
    'male': 'Male', 'female': 'Female',
    'low': 'Low', 'normal': 'Normal', 'high': 'High'
})

In [9]:
# -----------------------------
# 3. Binary columns
# -----------------------------
binary_cols = ['Fever', 'Cough', 'Fatigue', 'Difficulty Breathing']

for col in binary_cols:
    df[col] = df[col].map({'Yes': 1, 'No': 0})

In [10]:
df.head()

,Disease,Fever,Cough,Fatigue,Difficulty Breathing,Gender,Blood Pressure,Cholesterol Level,Outcome Variable
0,Influenza,1,0,1,1,Female,Low,Normal,Positive
1,Common Cold,0,1,1,0,Female,Normal,Normal,Negative
2,Eczema,0,1,1,0,Female,Normal,Normal,Negative
3,Asthma,1,1,0,1,Male,Normal,Normal,Positive
4,Eczema,1,0,0,0,Female,Normal,Normal,Positive

In [11]:
# -----------------------------
# 4. Gender
# -----------------------------
df['Gender'] = df['Gender'].map({'Female': 0, 'Male': 1})

In [12]:
# -----------------------------
# 5. Blood Pressure
# -----------------------------
df['Blood Pressure'] = df['Blood Pressure'].map({'Low': 0, 'Normal': 1, 'High': 2})

In [13]:
# -----------------------------
# 6. Cholesterol
# -----------------------------
df['Cholesterol Level'] = df['Cholesterol Level'].map({'Low': 0, 'Normal': 1, 'High': 2})

In [14]:
df.head()

,Disease,Fever,Cough,Fatigue,Difficulty Breathing,Gender,Blood Pressure,Cholesterol Level,Outcome Variable
0,Influenza,1,0,1,1,0,0,1,Positive
1,Common Cold,0,1,1,0,0,1,1,Negative
2,Eczema,0,1,1,0,0,1,1,Negative
3,Asthma,1,1,0,1,1,1,1,Positive
4,Eczema,1,0,0,0,0,1,1,Positive

In [15]:
df.head(10)

,Disease,Fever,Cough,Fatigue,Difficulty Breathing,Gender,Blood Pressure,Cholesterol Level,Outcome Variable
0,Influenza,1,0,1,1,0,0,1,Positive
1,Common Cold,0,1,1,0,0,1,1,Negative
2,Eczema,0,1,1,0,0,1,1,Negative
3,Asthma,1,1,0,1,1,1,1,Positive
4,Eczema,1,0,0,0,0,1,1,Positive
5,Influenza,1,1,1,1,0,1,1,Positive
6,Hyperthyroidism,0,1,0,0,0,1,1,Negative
7,Asthma,1,0,0,1,1,2,1,Positive
8,Allergic Rhinitis,0,1,1,0,0,1,0,Negative
9,Anxiety Disorders,0,1,0,0,0,1,2,Negative

In [16]:
# -----------------------------
# 7. Check missing values
# -----------------------------
print("Missing after mapping:\n", df.isnull().sum())

Missing after mapping:
 Disease                 0
Fever                   0
Cough                   0
Fatigue                 0
Difficulty Breathing    0
Gender                  0
Blood Pressure          0
Cholesterol Level       0
Outcome Variable        0
dtype: int64

In [17]:
# -----------------------------
# 8. Drop missing
# -----------------------------
df.dropna(inplace=True)

In [18]:
# -----------------------------
# 9. Save cleaned data
# -----------------------------
df.to_csv("cleaned_Dieases_data.csv", index=False)

In [19]:
print(df.head())

       Disease  Fever  Cough  Fatigue  Difficulty Breathing  Gender  \
0    Influenza      1      0        1                     1       0
1  Common Cold      0      1        1                     0       0
2       Eczema      0      1        1                     0       0
3       Asthma      1      1        0                     1       1
4       Eczema      1      0        0                     0       0

   Blood Pressure  Cholesterol Level Outcome Variable
0               0                  1         Positive
1               1                  1         Negative
2               1                  1         Negative
3               1                  1         Positive
4               1                  1         Positive

In [20]:
del df['Outcome Variable']

In [21]:
print(df.head())

       Disease  Fever  Cough  Fatigue  Difficulty Breathing  Gender  \
0    Influenza      1      0        1                     1       0
1  Common Cold      0      1        1                     0       0
2       Eczema      0      1        1                     0       0
3       Asthma      1      1        0                     1       1
4       Eczema      1      0        0                     0       0

   Blood Pressure  Cholesterol Level
0               0                  1
1               1                  1
2               1                  1
3               1                  1
4               1                  1

In [22]:
df.to_csv("cleaned_data.csv", index=False)